export const CREATE_NEW_WIDGET = "CREATE_NEW_WIDGET"
export const ADD_NEW_FIELD = "ADD_NEW_FIELD"
export const UPADTE_FIELD_POSITION = "UPADTE_FIELD_POSITION"
export const UPADTE_FIELD_SIZE = "UPADTE_FIELD_SIZE"